### ISSUE TITLE
Crashes on 1.16.3

### ISSUE THREAD

**Issue by crabdancing** [grondag/fermion#1]
Runtime log is [here](https://paste.ee/p/BAd8b).

**Comment by ghost** [comment]
Seem to a mod conflict or a old mod not working (minelittlepony)

**Comment by grondag** [comment]
Something is bundling an older version of Fermion that may not be compatible with 1.16.3.  Would try putting the [latest Fermion build] (https://www.curseforge.com/minecraft/mc-mods/fermion/files/3075652) in your mods folder and see if that helps:

**Comment by crabdancing** [comment]
sure :)

**Comment by crabdancing** [comment]
Yay it seems to work :D
